# All questions on classicmodels database
use classicmodels;
-- 1.List the total number of products in each product line.
select * from productlines;
select * from products;
select productline,count(productName) from products group by productline;

-- 2.Retrieve the total quantity of products ordered per order.
select * from orderdetails;
SELECT orderNumber, SUM(quantityOrdered) AS total_quantity FROM orderdetails GROUP BY orderNumber; 

-- 3. Find the number of orders for each order status.
select * from orders;
select status,count(orderNumber) from orders group by status;

--  4.Calculate the total revenue generated by each product.
select * from products;
select * from orderdetails;
select productCode,sum(quantityOrdered*priceEach) as total_revenue from orderdetails group by productCode ;


-- 5.Find the average credit limit for each country.
select * from customers;
select country, avg(creditLimit) from customers group by country;

-- 6. Find the top 3 customers with the highest total payments.
select * from payments;
select customerNumber, sum(amount) as total_amount from payments group by customerNumber order by total_amount desc limit 3;

-- 7. Find the total number of products supplied by each vendor.
select * from products;
select productVendor, count(productName) from products group by productVendor;

-- 8. Retrieve all customers sorted by country and then by customer name in ascending order.
select * from customers;
SELECT country,customerName FROM customers ORDER BY country, customerName ;

-- 9. List all orders sorted by order date in descending order.
select * from orders;
SELECT orderNumber, orderDate FROM orders ORDER BY orderDate DESC;

-- 10. Show the top 5 highest-paying customers.
select * from customers;
select customerName, creditLimit from customers order by creditLimit Desc limit 5;

-- 11. Retrieve product details sorted by quantity in stock in descending order.	
select * from products;
select productName,productDescription,quantityInStock from products order by quantityInStock desc;

-- 12. Get the employees sorted by their job title in alphabetical order(a to z)
select * from employees;
select employeeNumber,firstName,jobTitle from employees order by jobTitle;
 
 -- 13. Get the month-wise total sales for the year 2004.
 
-- 14. Display the orders placed on weekends (Saturday & Sunday).
